### ISSUE TITLE
On CI with Travis CI 

### ISSUE THREAD

**Issue by ZZP12** [varnerlab/JuCFMG#22]

**Comment by ZZP12** [comment]
### Adding CI to JuCFMG 

1. Travis CI serves our purpose? 
YES! 

2. Anyone tried it out? 
Yes! Peter tested it with his package [testseml.jl](https://github.com/ZZP12/testseml.jl/blob/master/.travis.yml). 
The `.travis.yml` looks like: 
```yml
language: julia

julia:
  - 1.1

python: 
  - 3.6 

os:
  - linux

notifications:
  email: false
before_install:
  - sudo apt-get -y install python3-pip 
  - pip3 install python-libsbml 
jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --color=yes --project -e 'using Pkg; Pkg.build(; verbose = true); Pkg.test(coverage=true)'
      after_success: skip
```
And with Travis CI, we can add an image to README.md to indicate if it passes tests: 
![Travic CI](https://travis-ci.com/ZZP12/testseml.jl.svg?branch=master)

3. How to do it? 
**repository owner** has to (and only the owner could) connect the repository to Travis CI by following [tutorial here](https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci-using-github). 
After the connection is set, the `.travis.yml` and the package can be updated anytime!

**Comment by Pooksoft** [comment]
This is awesome - I tested this out with a side project - works! One quick ?: I noticed that TravisCI is not free, it is actually pretty expensive. I found the following tutorial on CI in GitHb actions - is this an alternative?

https://lab.github.com/githubtraining/github-actions:-continuous-integration

**Comment by ZZP12** [comment]
Looks like `GitHub Actions` works with my test project! 

The `.yml` now looks as below: 
```yml 
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          sudo apt-get -y install python3-pip 
          pip3 install python-libsbml 
          julia --color=yes --project -e 'using Pkg; Pkg.build(; verbose = true); Pkg.test(coverage=true)'
```
All were generated by a GitHub Actions template except the last 3 lines which installed a python package and ran `test.jl` of the repository.
